.build: &build_image
  script:
    - if [ $TRAVIS_PULL_REQUEST == "false" ]; then ./.travis/docker_build.sh; fi

language: php
php:
  - '7.2'

env:
  - DB_CONNECTION=sqlite

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - docker run --rm -v ${TRAVIS_BUILD_DIR}:/app -w /app composer:1.6.5 composer install --ignore-platform-reqs
        - touch database/database.sqlite
        - php artisan migrate --force
    - stage: build develop
      if: branch = develop
      <<: *build_image
    - stage: build master
      if: branch = master
      <<: *build_image
